# Generated by Django 5.0.6 on 2024-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='vaccine name')),
                ('description', models.TextField(max_length=1024)),
                ('number_of_dosage', models.IntegerField(default=1)),
                ('intervel', models.IntegerField(default=0, help_text='pls provide interval in days')),
                ('storage_temperature', models.IntegerField(blank=True, help_text='provide the temperature', null=True)),
                ('minimun_age', models.IntegerField(default=0)),
            ],
        ),
    ]
